// Generated by Wrangler by running `wrangler types`

interface Env {
  PROXY_HOST_ROOT: string;
  API_HOST: string;
  ACCOUNT_ID: string;
  ANALYTICS_ACCOUNT_TOKEN: string;
  PROXY_DB: D1Database;
}
