// Generated by Wrangler on Sun Nov 10 2024 18:12:50 GMT-0500 (Eastern Standard Time)
// by running `wrangler types`

interface Env {
	PROXY_HOST_ROOT: "proxy.workerspy.dev";
	PROXY_DB: D1Database;
}
