// Generated by Wrangler by running `wrangler types`

interface Env {
  PROXY_HOST_ROOT: string;
  REQUESTS_WEBSOCKET: DurableObjectNamespace<
    import("./src/index").RequestsWebSocket
  >;
  PROXY_DB: D1Database;
  ANALYTICS_ENGINE: AnalyticsEngineDataset;
}
